INSERT INTO `bet365`.`sport` (`idSport`,`name`) VALUES (1, 'Futebol Virtual');
INSERT INTO `bet365`.`sport` (`idSport`,`name`) VALUES (2, 'Futebol');

INSERT INTO `bet365`.`market` (`idMarket`, `name`, `idSport`) VALUES (1, 'Vencedor do Jogo', 1);
INSERT INTO `bet365`.`market` (`idMarket`, `name`, `idSport`) VALUES (2, 'Número de Gols', 1);
INSERT INTO `bet365`.`market` (`idMarket`, `name`, `idSport`) VALUES (3, 'Resultado Correto', 1);
INSERT INTO `bet365`.`market` (`idMarket`, `name`, `idSport`) VALUES (4, 'Time a Marcar Primeiro', 1);
INSERT INTO `bet365`.`market` (`idMarket`, `name`, `idSport`) VALUES (5, 'Intervalo - Resultado Correto', 1);
INSERT INTO `bet365`.`market` (`idMarket`, `name`, `idSport`) VALUES (6, 'Total de Gols', 1);
INSERT INTO `bet365`.`market` (`idMarket`, `name`, `idSport`) VALUES (7, 'Para Ambos os Times Marcarem', 1);
INSERT INTO `bet365`.`market` (`idMarket`, `name`, `idSport`) VALUES (8, 'Para o Time Da Casa Marcar', 1);
INSERT INTO `bet365`.`market` (`idMarket`, `name`, `idSport`) VALUES (9, 'Para o Time  Visitante Marcar', 1);

INSERT INTO `bet365`.`competition` (`idCompetition`, `description`, `alternativeDescription`, `idSport`) VALUES (20120650, 'Copa do Mundo', 'Campeonato do Mundo', 1);

INSERT INTO `bet365`.`typemarket` (`idTypeMarket`,`label`) VALUES (1, 'over 0.5', 2);
INSERT INTO `bet365`.`typemarket` (`idTypeMarket`,`label`) VALUES (2, 'under 0.5', 2);
INSERT INTO `bet365`.`typemarket` (`idTypeMarket`,`label`) VALUES (3, 'over 1.5', 2);
INSERT INTO `bet365`.`typemarket` (`idTypeMarket`,`label`) VALUES (4, 'under 1.5', 2);
INSERT INTO `bet365`.`typemarket` (`idTypeMarket`,`label`) VALUES (5, 'over 2.5', 2);
INSERT INTO `bet365`.`typemarket` (`idTypeMarket`,`label`) VALUES (6, 'under 2.5', 2);
INSERT INTO `bet365`.`typemarket` (`idTypeMarket`,`label`) VALUES (7, 'over 3.5', 2);
INSERT INTO `bet365`.`typemarket` (`idTypeMarket`,`label`) VALUES (8, 'under 3.5', 2);

INSERT INTO `bet365`.`typemarket` (`idTypeMarket`,`label`) VALUES (9, 'gol 0');
INSERT INTO `bet365`.`typemarket` (`idTypeMarket`,`label`) VALUES (10, 'gol 1');
INSERT INTO `bet365`.`typemarket` (`idTypeMarket`,`label`) VALUES (11, 'gol 2');
INSERT INTO `bet365`.`typemarket` (`idTypeMarket`,`label`) VALUES (12, 'gol 3');
INSERT INTO `bet365`.`typemarket` (`idTypeMarket`,`label`) VALUES (13, 'gol 4');
INSERT INTO `bet365`.`typemarket` (`idTypeMarket`,`label`) VALUES (14, 'ambas sim');
INSERT INTO `bet365`.`typemarket` (`idTypeMarket`,`label`) VALUES (15, 'ambas nao');
INSERT INTO `bet365`.`typemarket` (`idTypeMarket`,`label`) VALUES (16, '0x0 FT');
INSERT INTO `bet365`.`typemarket` (`idTypeMarket`,`label`) VALUES (17, '1x1 FT');
INSERT INTO `bet365`.`typemarket` (`idTypeMarket`,`label`) VALUES (18, '2x2 FT');
INSERT INTO `bet365`.`typemarket` (`idTypeMarket`,`label`) VALUES (19, '1x0 FT');
INSERT INTO `bet365`.`typemarket` (`idTypeMarket`,`label`) VALUES (20, '2x0 FT');
INSERT INTO `bet365`.`typemarket` (`idTypeMarket`,`label`) VALUES (21, '2x1 FT');
INSERT INTO `bet365`.`typemarket` (`idTypeMarket`,`label`) VALUES (22, '3x0 FT');
INSERT INTO `bet365`.`typemarket` (`idTypeMarket`,`label`) VALUES (23, '3x1 FT');
INSERT INTO `bet365`.`typemarket` (`idTypeMarket`,`label`) VALUES (24, '4x0 FT');
INSERT INTO `bet365`.`typemarket` (`idTypeMarket`,`label`) VALUES (25, '0x1 FT');
INSERT INTO `bet365`.`typemarket` (`idTypeMarket`,`label`) VALUES (26, '0x2 FT');
INSERT INTO `bet365`.`typemarket` (`idTypeMarket`,`label`) VALUES (27, '1x2 FT');
INSERT INTO `bet365`.`typemarket` (`idTypeMarket`,`label`) VALUES (28, '0x3 FT');
INSERT INTO `bet365`.`typemarket` (`idTypeMarket`,`label`) VALUES (29, '1x3 FT');
INSERT INTO `bet365`.`typemarket` (`idTypeMarket`,`label`) VALUES (30, '0x4 FT');
INSERT INTO `bet365`.`typemarket` (`idTypeMarket`,`label`) VALUES (31, '0x0 HT');
INSERT INTO `bet365`.`typemarket` (`idTypeMarket`,`label`) VALUES (32, '1x1 HT');
INSERT INTO `bet365`.`typemarket` (`idTypeMarket`,`label`) VALUES (33, '1x0 HT');
INSERT INTO `bet365`.`typemarket` (`idTypeMarket`,`label`) VALUES (34, '2x0 HT');
INSERT INTO `bet365`.`typemarket` (`idTypeMarket`,`label`) VALUES (35, '0x1 HT');
INSERT INTO `bet365`.`typemarket` (`idTypeMarket`,`label`) VALUES (36, '0x2 HT');
INSERT INTO `bet365`.`typemarket` (`idTypeMarket`,`label`) VALUES (37, 'outro HT');
INSERT INTO `bet365`.`typemarket` (`idTypeMarket`,`label`) VALUES (38, 'mandante HT');
INSERT INTO `bet365`.`typemarket` (`idTypeMarket`,`label`) VALUES (39, 'empate HT');
INSERT INTO `bet365`.`typemarket` (`idTypeMarket`,`label`) VALUES (40, 'visitante HT');
INSERT INTO `bet365`.`typemarket` (`idTypeMarket`,`label`) VALUES (41, 'mandante FT');
INSERT INTO `bet365`.`typemarket` (`idTypeMarket`,`label`) VALUES (42, 'empate FT');
INSERT INTO `bet365`.`typemarket` (`idTypeMarket`,`label`) VALUES (43, 'visitante FT');
INSERT INTO `bet365`.`typemarket` (`idTypeMarket`,`label`) VALUES (44, 'casa marca sim');
INSERT INTO `bet365`.`typemarket` (`idTypeMarket`,`label`) VALUES (45, 'casa marca nao');
INSERT INTO `bet365`.`typemarket` (`idTypeMarket`,`label`) VALUES (46, 'visitante marca sim');
INSERT INTO `bet365`.`typemarket` (`idTypeMarket`,`label`) VALUES (47, 'visitante marca nao');
INSERT INTO `bet365`.`typemarket` (`idTypeMarket`,`label`) VALUES (48, 'casa marca primeiro sim');
INSERT INTO `bet365`.`typemarket` (`idTypeMarket`,`label`) VALUES (49, 'casa marca primeiro nao');